[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fuzz]
runs = 1000

[fmt]
multiline_func_header = "params_first"
override_spacing = true

[lint]
exclude_lints = ["erc20-unchecked-transfer", "unused-import"]